<title>Criar tabelas</title>

<?
$con_string = "host=localhost port=5432 dbname=jclDb user=henrique ";
$bdcon4 = pg_connect ($con_string) or die ("Não conectado ao banco de dados<br>".pg_last_error());
$query = "CREATE TABLE aluno (
id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 1 INCREMENT BY 1),
	name_aluno varchar(25) not null ,
	dn varchar(25) not null,
	cpf int not null,
	telefone varchar(25) not null,
	wpp varchar(25) not null,
	timestamp timestamp default current_timestamp
)";
pg_query($query) or
die ("Query Failed.<br>".pg_last_error());
$query = "CREATE TABLE cursos(
	id_cursos int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 1 INCREMENT BY 1),
	 courses varchar(25) not null
  )";
pg_close($conexao);
?>



